apiVersion: apps/v1
kind: Deployment
metadata:
 name: myonlineapp-deploy
 labels:
   app: myonlineapp
spec:
  replicas: 3
  selector:
    matchLabels:
        app: myonlineapp
  template:
    metadata:
       labels:
        app: myonlineapp
    spec:
      containers:
      - name: myonlineapp-container
        image:  maha4iac/myonlineapp:1
        ports:
        - containerPort: 8080